# Generated by Django 6.0.4 on 2026-04-15 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'start_time', 'end_time', '-average_rating'], name='idx_running_top_rated'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'start_time', 'end_time', '-created_at'], name='idx_running_latest'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_featured', '-created_at'], name='idx_featured'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', '-created_at'], name='idx_category_latest'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='idx_latest'),
        ),
    ]
