# Generated by Django 6.0.4 on 2026-04-15 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_slug_project_idx_running_top_rated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='idx_running_top_rated',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_running_latest',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_latest',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-average_rating'], name='idx_running_top_rated'),
        ),
    ]
