# Generated by Django 5.2.13 on 2026-04-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_category_options_alter_project_options_and_more'),
        ('projects', '0003_remove_project_idx_running_top_rated_and_more'),
    ]

    operations = [
    ]
