# Generated by Django 6.0.4 on 2026-04-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_merge_20260416_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_created_775fe7_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_categor_1be16a_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_is_feat_9105d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_is_canc_ba099b_idx',
        ),
    ]
