# Generated by Django 6.0.4 on 2026-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activation'), ('reset', 'Password Reset')], default='activation', max_length=20),
        ),
    ]
