# Generated by Django 5.2.13 on 2026-04-16 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Egyptian number (e.g., 01012345678).', regex='^01[0-2,5]{1}[0-9]{8}$')]),
        ),
    ]
